allowBuilds:
  esbuild: set this to true or false
  sharp: set this to true or false
  workerd: set this to true or false
minimumReleaseAgeExclude:
  - '@ouraihub/llm@0.2.0'
  - '@ouraihub/llm@0.2.1'
